# minecraft/Dockerfile
FROM itzg/minecraft-server

ENV EULA=TRUE
ENV MEMORY=2G

# Optional: Kopiere Konfigurationsdateien oder Mods
# COPY mods/ /data/mods/
# COPY config/ /data/config/

EXPOSE 25565
